### ISSUE TITLE
pokémon with 600+ hours remaining 

### ISSUE THREAD

**Issue by juniu** [favll/pogom#260]
a lot of pokémon showing up with 600h+ remaining do expire (slowpoke, bellsprout, meowth...)
![image](https://cloud.githubusercontent.com/assets/20997963/17634815/ba4d8eee-60aa-11e6-9cff-cbf9bff8ea10.png)

**Comment by Jones1337** [comment]
+1 same here... also 595h :D

**Comment by serfma** [comment]
Can also confirm this. It appears Niantic is doing some more changing to their API?

**Comment by asdfMaciej** [comment]
Can confirm as well.

**Comment by Mickey32111** [comment]
+1
Literally just logged on to report this.

**Comment by TilkIG** [comment]
+1 
Signed up to Github to confirm.
![vaporeon](https://cloud.githubusercontent.com/assets/20998451/17635748/7a467642-60d9-11e6-9d4b-54cfd7ae8a82.png)

(If only that vaporeon didn't flee after using all my Ultra balls and Rzz Berries)

**Comment by SM411** [comment]
I guess there is enough confirmations, but this also appears on my radar.

**Comment by compuguy** [comment]
It could be a lot of things, including them changing how they encode their expiry times.

**Comment by dikkedeur** [comment]
i can totally confirm them...

**Comment by joeubi** [comment]
+1

**Comment by seikur0** [comment]
Guys, don't make a huge issue out of it, it's just a variable overflow. Nothing changed in the niantic servers, just the protos has to be changed and updated T_T

**Comment by djv2** [comment]
same here :-1:

**Comment by SantoDE** [comment]
can confirm. Not a huge deal tough.

**Comment by djv2** [comment]
change protos from int32 to int64 to fix overflow in proto

**Comment by Mickey32111** [comment]
@djv2 yeah just saw the pull request. Where is this stored on pogom?

Also, how can I go about removing the anomalies from my db so they don't show anymore?

**Comment by djv2** [comment]
@Mickey32111 .\pogom\pgoapi\protos\POGOProtos_src\Map\Pokemon\WildPokemon.proto

**Comment by Mickey32111** [comment]
@djv2 kudos to you :)

**Comment by seikur0** [comment]
You can't just change the protos, you need to recompile them ;)

**Comment by SantoDE** [comment]
Kudos to you that you guys figured it out. Dunno how you guys figured it :-D

**Comment by asdfMaciej** [comment]
Cheers, thanks for this @djv2!

**Comment by Jones1337** [comment]
f**k can u please explain shortly how to recompile? i'm not familiar with python ;'(
Or just make a new commit :-D

**Comment by seikur0** [comment]
Had to recompile this for my map anyway: https://github.com/favll/pogom/pull/264

**Comment by Mickey32111** [comment]
How can I remove the Pokemon with the 600 hour expiry time from my db?

**Comment by seikur0** [comment]
Excel? idk xD I'm not using this Tool haha

**Comment by compuguy** [comment]
@Mickey32111 thats the $100 question....

**Comment by Mickey32111** [comment]
@compuguy @seikur0 
http://sqlitebrowser.org/ can be used to view the database, there is a field called disappear time, I'm gonna try to delete all of the entries that are set to disappear next month (in 600 hours)

**Comment by compuguy** [comment]
@Mickey32111 I was able to remove the ones that are dated around 2016-09-06 using this query `delete from pokemon where disappear_time like '2016-09-06 14:56:22.527000';`

**Comment by turner-curtis** [comment]
if you are using mysql you can try something like this:
update pokemon
	set disappear_time = '2016-08-12 18:04:00'
	where disappear_time > '2016-08-13 00:00:00';

**Comment by Mickey32111** [comment]
@compuguy I'm so confused. I've run all sorts of queries and even deleted them manually, yet one or two always remain.

**Comment by TheHippo** [comment]
Possible fix: AeonLucid/POGOProtos/pull/184

**Comment by Mickey32111** [comment]
The server is 100% re-adding these records to the db, I can't think of any other explanation

**Comment by Jones1337** [comment]
@seikur0 can u please PR your implementation of search algorithm with multiple workers, which fix the "received valid response but without any data. Possibly rate-limited?" message.

**Comment by seikur0** [comment]
I'm not using pgoapi, just their unknown6 functions. So it would be too much work to do that, sry.

**Comment by Mickey32111** [comment]
@seikur0 even after using your recomplied `Pokemon_pb2.py`, and using a db before it happened I'm still getting 592h pokemon's appearing.

**Comment by seikur0** [comment]
That's true, just tested it as well. In that case the protos is correct and it is being sent as 32bit value already. And it must be solved in the pgoapi.

**Comment by dikkedeur** [comment]
i changed it to 64, still got the same problem.
i did even dropped my DB to see if that was working better.
so on a fresh new DB same thing occur, and most important.. on the exact same spots as before..
thats odd.

**Comment by seikur0** [comment]
It's not odd, the spots are just spawn points with higher than 15min staytimes. Forget the 64 thing, the overflow occurs already at Niantic, server sided. I edited my comment above with a pull request, that fixes it.

**Comment by Greg117** [comment]
@seikur0 Looks like your fix works.  Just need to drop the database and re-collect for it to work properly.  I'm assuming that this will discard these pokemon until there is an api fix though right?

**Comment by Jones1337** [comment]
i'm getting pokemons with disappearence time of 1h 15min :/ ... so it's not fixed i think

**Comment by Jones1337** [comment]
looks like it's not fixed yet or it's my failure... now i get pokemons with disappearence time of 1h+

**Comment by seikur0** [comment]
You're wrong, the api is fine, it's up to the individual programs, how to handle these values, before they were returned negative, now they're positive. And this tool here doesn't throw them away, it sets these pokemon to 15 minutes time left as it should. In half a month the values will be returned negative again :P

**Comment by qwerty0123** [comment]
So, just noticed this, but they all show up in the same spots on my maps, as in, exactly the same. New type of spawn?

**Comment by iMagooo** [comment]
Are these pokemon there for that time or do they disappear after 15 minutes?

**Comment by MzHub** [comment]
The fact that the point where the behavior changes is exactly when the time_till_hidden hits 15 minutes, or 900000 ms, makes it too arbitrary in my opinion, to be a low level overflow issue. Exactly 15 minutes does not really match any common overflow points..?

**Comment by xiongqc** [comment]
tried the 32->64 change and a fresh clone. no difference

**Comment by Chrallas** [comment]
Sorry for creating a new issue my Phone didnt update thread issues.

But I tried to drop all dbs and recollect data it works for a While but then adding theese 500+h spawns but it deletes The old ones and not adding them again. What would happend if we somehow tried to force scan.py file to set maximum spawn timer to 15 minutes and min to 0?

**Comment by Mickey32111** [comment]
@seikur0's commit has been merged with the master branch, you can now pull the change if you haven't implemented it manually yet.

**Comment by Chrallas** [comment]
> Mickey32111 commented 3 minutes ago
@seikur0's commit has been merged with the master branch, you can now pull the change if you haven't implemented it manually yet.

Where is his merge? where can I find the testing fix?

**Comment by Mickey32111** [comment]
@Chrallas 

9e9651ea1ce449b76e0573240df6964436bf6d17
